### ISSUE TITLE
I would like to know how to install nut.

### ISSUE THREAD

**Issue by Edison4mobile** [42ity/nut#106]
It seems all hyper links are broken.
Please give me detailed instruction.
Thanks.

**Comment by jimklimov** [comment]
This is a fork for a particular application of NUT (and to stage in practice some updates for community).
Please take a look at the primary upstream : https://github.com/networkupstools/nut
There is a helpful mailing list in particular, that can help with many different platforms you might want to install on. In short, to start with the answer - it usually needs details on where you want to install it (OS) and how (packages or from source?)

**Comment by Edison4mobile** [comment]
./autogen
./configure
./make
./sudo make install
